name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v3
    
    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    # Install CMake
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    # Setup LLVM/Clang
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
        
    # Run Build
    - name: Run Build
      run: |
        cd ${{github.workspace}}
        .\build.ps1 --debug --clean
    
    # Copy necessary DLLs
    - name: Copy DLLs
      run: |
        cp "C:/Program Files/dotnet/host/fxr/8.0.12/hostfxr.dll" ${{github.workspace}}/build/tests/Debug/
        cp "C:/Program Files/dotnet/shared/Microsoft.NETCore.App/8.0.12/*" ${{github.workspace}}/build/tests/Debug/

    # Run Tests
    - name: Run Tests
      run: |
        cd ${{github.workspace}}/build
        ctest -C Debug --output-on-failure
